export const TYPES = {
  SET_MOVIES: "SET_MOVIES",
  SET_INIT_MOVIES: "SET_INIT_MOVIES",
  SET_MOVIES_FILTERED: "SET_MOVIES_FILTERED",
  DELETE_MOVIE: "DELETE_MOVIE",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_TOGGLE_LIKE: "SET_TOGGLE_LIKE",
  SET_TOGGLE_DISLIKE: "SET_TOGGLE_DISLIKE",
};

export default TYPES;
